# Generated by Django 5.1.1 on 2024-09-28 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sendmessage_delete_am_delete_enquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sendMessage',
            new_name='save',
        ),
    ]
