# Generated by Django 5.1.1 on 2024-09-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_sendmessage_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(max_length=20)),
                ('qemail', models.CharField(max_length=40)),
                ('qmobile', models.CharField(max_length=15)),
                ('qspecialnote', models.CharField(max_length=400)),
            ],
        ),
    ]
