# Generated by Django 5.1.1 on 2024-10-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_quote_qservice_alter_quote_qemail_alter_quote_qname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='mobile',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
