# Generated by Django 5.1.1 on 2024-10-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_save_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='qspecialnote',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='save',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
