# Generated by Django 5.1.1 on 2024-10-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_save_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='qservice',
        ),
    ]
