# Generated by Django 5.1.1 on 2024-10-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_quote_qservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='qservice',
            field=models.CharField(choices=[('not selected', 'Service'), ('S1', 'Service 1'), ('S2', 'Service 2'), ('S3', 'Service 3')], default='not selected', max_length=12),
        ),
    ]
