# Generated by Django 5.1.1 on 2024-10-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_quote_qservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='qemail',
            field=models.CharField(max_length=30),
        ),
    ]
