# Generated by Django 5.1.1 on 2024-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_quote_qemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='qemail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='qspecialnote',
            field=models.TextField(max_length=500),
        ),
    ]
